name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
        
    - name: Toolchain info
      run: |
        cargo --version --verbose
        rustc --version
        cargo clippy --version
        
    - name: Lint
      run: |
        cargo fmt -- --check
        cargo clippy -- -D warnings
        
    - name: Test
      run: |
        cargo check
        cargo test --all
    
    - name: Build (Release)
      run: cargo build --release
